### ISSUE TITLE
📢 [help wanted] implement RISC-V cryptography (sub-)extensions

### ISSUE THREAD

**Issue by stnolting** [stnolting/neorv32#1034]
## Help Wanted!

Now that we have some basic RISC-V cryptography ISA extension support (#1033), it would be great to also add support for the remaining sub-extensions.

* [x] `Zbkb` - bit manipulation instructions for cryptography (#1037)
* [x] `Zbkc` - carry-less multiplications (#1038)
* [x] `Zkn` - shorthand for `Zbkb` + `Zbkc` + `Zbkx` + `Zbkne` + `Zbknd` + `Zknh` (#1039)
* [x] `Zksed` - ShangMi block cipher operations (#1040)
* [x] `Zksh` - ShangMi hash functions (#1040)
* [x] `Zks` - shorthand for `Zbkb` + `Zbkc` + `Zbkx` + `Zksed` + `Zksh` (#1040)
* [x] `Zkt` - data-independent execution latency (#1036)
* [ ] ~`Zkr` - entropy source~

Any kind of help is most welcome! :)
